# # .github/workflows/terraform-oidc.yml

# name: Reusable Terraform Azure Deployment (OIDC)

# on:
#   workflow_call:
#     inputs:
#       terraform_dir:
#         required: true
#         type: string
#       tfvars_file:
#         required: true
#         type: string

#     secrets:
#       ARM_CLIENT_ID:
#         required: true
#       ARM_TENANT_ID:
#         required: true
#       ARM_SUBSCRIPTION_ID:
#         required: true

# permissions:
#   id-token: write
#   contents: read

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v3
#         with:
#           terraform_version: 1.6.6

#       - name: Azure Login with OIDC
#         uses: azure/login@v2
#         with:
#           client-id: ${{ secrets.ARM_CLIENT_ID }}
#           tenant-id: ${{ secrets.ARM_TENANT_ID }}
#           subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

#       - name: Terraform Init
#         working-directory: ${{ inputs.terraform_dir }}
#         run: terraform init
#         env:
#           ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
#           ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
#           ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
#           ARM_USE_OIDC: true

#       - name: Terraform Validate
#         working-directory: ${{ inputs.terraform_dir }}
#         run: terraform validate
#         env:
#           ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
#           ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
#           ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
#           ARM_USE_OIDC: true

#       - name: Terraform Plan
#         working-directory: ${{ inputs.terraform_dir }}
#         run: terraform plan -var-file="${{ inputs.tfvars_file }}" -out=tfplan
#         env:
#           ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
#           ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
#           ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
#           ARM_USE_OIDC: true

#       - name: Terraform Apply
#         working-directory: ${{ inputs.terraform_dir }}
#         run: terraform apply -auto-approve tfplan
#         env:
#           ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
#           ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
#           ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
#           ARM_USE_OIDC: true
